apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- https://github.com/metal3-io/baremetal-operator/config/namespace?ref=release-0.8&timeout=120s
- https://github.com/metal3-io/baremetal-operator/ironic-deployment/base?ref=release-0.8&timeout=120s

configMapGenerator:
- envs:
  - ipxe-configmap.env
  name: ipxe-configmap
  behavior: create

patches:
- path: ipxe-builder-patch.yaml
